version: '3.8'

services:
  app:
    build:
      context: .
    container_name: symfony_app
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/app.ini
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - DATABASE_URL=mysql://root:root@db:3306/${MYSQL_DATABASE:-symfony}?serverVersion=8.0.27&charset=utf8mb4
    networks:
      - symfony_network

  db:
    image: mysql:8.0.27
    container_name: symfony_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${MYSQL_DATABASE:-symfony}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - symfony_network

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - symfony_network



  node:
    image: node:18
    container_name: symfony_node
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: yarn watch
    depends_on:
      - app
    networks:
      - symfony_network

volumes:
  mysql_data:

networks:
  symfony_network:
    driver: bridge