version: '3'

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8089:80"
    volumes:
      - ./:/code
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
  php:
    build: .
    environment:
      - DATABASE_URL="mysql://root:root@mysql:3306/SGRH1?serverVersion=8.0.27&charset=utf8mb4"
    volumes:
      - ./:/code
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root # ⬅︎ 🚨
      MYSQL_DATABASE: SGRH1
      MYSQL_USER: user # ⬅︎ 🚨
      MYSQL_PASSWORD: password # ⬅︎ 🚨
    volumes:
      - data:/var/lib/mysql

  adminer-Sql:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - mysql
networks:
  default:
    name: shared

volumes:
  data: