parameters:
    ZOOM_CLIENT_ID: '%env(ZOOM_CLIENT_ID)%'
    ZOOM_CLIENT_SECRET: '%env(ZOOM_CLIENT_SECRET)%'
    ZOOM_ACCOUNT_ID: '%env(ZOOM_ACCOUNT_ID)%'

services:
    App\Service\ZoomService:
        autowire: true
        autoconfigure: true
    Symfony\Component\Finder\Finder: ~

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
